# Generated by Django 4.2.27 on 2025-12-25 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id_prodi', models.BigAutoField(primary_key=True, serialize=False)),
                ('prodi', models.CharField(max_length=100)),
                ('jenjang', models.CharField(choices=[('D3', 'Diploma 3'), ('S1', 'Sarjana')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Program Studi',
                'verbose_name_plural': 'Program Studi',
                'db_table': 'prodi',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nim', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tempat', models.CharField(max_length=50, verbose_name='Tempat Lahir')),
                ('tgl_lahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('tahun_masuk', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('no_telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id_prodi', models.ForeignKey(db_column='id_prodi', on_delete=django.db.models.deletion.CASCADE, to='core.prodi')),
            ],
            options={
                'verbose_name': 'Mahasiswa',
                'verbose_name_plural': 'Mahasiswa',
                'db_table': 'mahasiswa',
                'ordering': ['-tahun_masuk', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('mahasiswa', 'Mahasiswa')], default='mahasiswa', max_length=20)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('nim', models.OneToOneField(blank=True, db_column='nim', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.mahasiswa')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
    ]
